# Generated by Django 3.2.8 on 2021-11-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='address',
            new_name='adress',
        ),
    ]
